### ISSUE TITLE
Implement an ability to specify authenticated userIDs

### ISSUE THREAD

**Issue by sleshchenko** [openshift/oauth-proxy#168]
Hello, I'm from Eclipse Che team and we're trying to use OpenShift OAuth proxy for our needs.

In our scenario we need OpenShift OAuth Proxy to pass-user-bearer-token and this an ability exists :tada: 
But we also need to restrict OpenShift OAuth Proxy to allow only one specific user.

I wonder if there are any thoughts against implementing an ability to specify authentication userIDs in the same way OpenShift OAuth proxy provides with `-authenticated-emails-file`.
Like `-authenticated-ids-file` or even `-authenticated-ids`.

**Comment by stlaz** [comment]
Hi,
As per https://github.com/openshift/oauth-proxy/issues/83, the authenticated emails don't really appear to work with the OpenShift auth provider and we would really like to scope the proxy down, so this is not likely to change. It's even questionable whether the downscoping is going to happen since "we" is "I" at this moment.

You might still be able to use the `--openshift-sar` option to do what you mean to do.
