### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by eraserx99** [openshift/oauth-proxy#73]
Hi,

  Lately, we started to test the oauth-proxy with the sidecar demo. We tried the openshift/oauth-proxy:v1.0.0 ~ latest, but we always got the issue below.

> 2018/06/10 00:41:00 oauthproxy.go:238: Cookie settings: name:_oauth_proxy secure(https):true httponly:true expiry:168h0m0s domain:<default> refresh:disabled
> 2018/06/10 00:41:00 http.go:56: HTTP: listening on 127.0.0.1:4180
> 2018/06/10 00:41:00 http.go:96: HTTPS: listening on [::]:8443
> 2018/06/10 00:41:49 oauthproxy.go:635: error redeeming code (client:10.131.0.1:55816): Post https://openshift.k8s.OURDOMAIN.com:8443/oauth/token:  x509: certificate signed by unknown authority
> 2018/06/10 00:41:49 oauthproxy.go:434: ErrorPage 500 Internal Error Internal Error

  As far as we know, the oauth-proxy would take the /var/run/secrets/kubernetes.io/serviceaccount/ca.crt as the openshift-ca by default. We copied that file out of the container and used OpenSSL to run against the server as below,

openssl s_client -connect openshift.k8s.OURDOMAIN.com:8443 -CAfile ca.crt

  The verify return code is 0 and it looked good (if we don't pass the CAfile, the verify return code would be 19 (self signed certificate in certificate chain))

> SSL-Session:
>     Protocol  : TLSv1.2
>     Cipher    : ECDHE-RSA-AES128-GCM-SHA256
>     Session-ID: 2DEC4D9600F1A1BBF2467391B1D79C7D8C21A1011D0FB6758BFD5D45393DA59E
>     Session-ID-ctx:
>     Master-Key: E3A3247A40AE91ED6339D0636A2B918A71F46ED09E8C5AB368338FEDA3B0FD4B528A49140C0463CA18C2A39ADB183244
>     TLS session ticket:
>     0000 - 0a 16 e9 90 30 b6 82 50-e8 4a ba 45 a0 1a c8 50   ....0..P.J.E...P
>     0010 - d3 0d 6a 3e ce a8 7a 49-8f 26 a5 23 6c 9d 9d b6   ..j>..zI.&.#l...
>     0020 - 7a 30 61 b2 1b 83 f1 fa-1c dc 6e d4 81 61 51 ef   z0a.......n..aQ.
>     0030 - e1 e7 bb e2 03 58 8b 38-0c 12 2d ce 5c f7 92 f3   .....X.8..-.\...
>     0040 - 22 01 55 82 c0 79 ad 4e-d5 c8 36 99 9b 15 2c bb   ".U..y.N..6...,.
>     0050 - 74 55 92 24 2c 22 11 4f-bf ae 36 3f b1 00 9c 41   tU.$,".O..6?...A
>     0060 - 57 e8 bf 58 46 ba cf ac-c3 3a 2d 93 bf ad 87 f6   W..XF....:-.....
>     0070 - 49 bb f5 10 26 c4 e3 fe-                          I...&...
> 
>     Start Time: 1528599113
>     Timeout: 300 (sec)
>     Verify return code: 0 (ok)

  We kind of hit the roadblock now. Any help would be appreciated!

  BTW, here is our OpenShfit version information,
 
  openshift v3.7.1+c2ce2c0-1
  kubernetes v1.7.6+a08f5eeb62

Steve

**Comment by eraserx99** [comment]
I think I just figured out the theory (why it didn't work).

  Lately, our system administrator just replaced the self-signed cert with a commercial one. However, I don't think that the right ca cert has been re-deployed to OpenShift. That's why the container still gets the original self-signed ca cert. Of course, it cannot verify the commercial server certificate. 

  Regarding the openssl test I posted earlier, I also need to add the -servername parameter (for SNI) to test. It should look like,

openssl s_client -servername openshift.k8s.OURDOMAN.com -connect openshift.k8s.OURDOMAIN.com:8443 -CAfile ca.crt

  I will check with our system administrator soon.

**Comment by razvan-miron** [comment]
Can you post your fix? I have the same issue. Where did you add the ca file? To named certificates?

**Comment by razvan-miron** [comment]
I have found the fix by appending the ca intermediate certificate to the custom cert file. 
Here:

```
namedCertificates:
  - certFile: /etc/origin/master/named_certificates/master_cert.pem
```

**Comment by JustinKuli** [comment]
We found this issue could occur in the Tekton Dashboard on OpenShift after [changing the cluster's default ingress certificate](https://docs.openshift.com/container-platform/4.3/authentication/certificates/replacing-default-ingress-certificate.html) which was used by the OpenShift oauth server. The issue seems to be that the oauth-proxy will use the service account certificate `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` by default, which works when the oauth server is using the original certificate during installation, but is not updated with the new certificate authority information after making that change.

I think the problem can be worked around by an adjusted configuration of the oauth-proxy container, and [using a configmap with an updated certificate bundle populated by OpenShift](https://docs.openshift.com/container-platform/4.3/networking/configuring-a-custom-pki.html#certificate-injection-using-operators_configuring-a-custom-pki). After mounting the bundle from the configmap into the container, I found that adding two `--openshift-ca` arguments works well: one pointing to the (default) certificate at `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`, and another pointing to the new certificate bundle.

There is a more detailed patch example in https://github.com/tektoncd/dashboard/issues/1603.
